# SPDX-FileCopyrightText: 2020-2022 Alexandru Fikl <alexfikl@gmail.com>
#
# SPDX-License-Identifier: MIT

from typing import Any, Callable, Optional, Tuple, Union, TYPE_CHECKING

import numpy as np

ScalarType = np.float64
FloatOrScalar = Union[float, ScalarType]

if TYPE_CHECKING:
    ArrayType = np.ndarray[Any, np.dtype[ScalarType]]
else:
    ArrayType = np.ndarray

def cg_default(arg0: object) -> None: ...
def cg_descent(
    x: ArrayType,
    grad_tol: FloatOrScalar,
    param: Optional["cg_parameter"],
    value: Callable[[ArrayType], ScalarType],
    grad: Callable[[ArrayType, ArrayType], None],
    valgrad: Optional[Callable[[ArrayType, ArrayType], ScalarType]],
    callback: Optional[Callable[["cg_iter_stats"], int]],
    work: Optional[ArrayType],
) -> Tuple[ArrayType, "cg_stats", bool]: ...

class cg_iter_stats:
    def __init__(self) -> None: ...
    @property
    def alpha(self) -> ScalarType: ...
    @property
    def d(self) -> ArrayType: ...
    @property
    def f(self) -> ScalarType: ...
    @property
    def g(self) -> ArrayType: ...
    @property
    def iter(self) -> int: ...
    @property
    def x(self) -> ArrayType: ...

class cg_parameter:
    def __init__(self) -> None: ...
    @property
    def AWolfe(self) -> int: ...
    @AWolfe.setter
    def AWolfe(self, val: int) -> None: ...
    @property
    def AWolfeFac(self) -> ScalarType: ...
    @AWolfeFac.setter
    def AWolfeFac(self, val: FloatOrScalar) -> None: ...
    @property
    def AdaptiveBeta(self) -> int: ...
    @AdaptiveBeta.setter
    def AdaptiveBeta(self, val: int) -> None: ...
    @property
    def BetaLower(self) -> ScalarType: ...
    @BetaLower.setter
    def BetaLower(self, val: FloatOrScalar) -> None: ...
    @property
    def CubicCutOff(self) -> ScalarType: ...
    @CubicCutOff.setter
    def CubicCutOff(self, val: FloatOrScalar) -> None: ...
    @property
    def ExpandSafe(self) -> ScalarType: ...
    @ExpandSafe.setter
    def ExpandSafe(self, val: FloatOrScalar) -> None: ...
    @property
    def LBFGS(self) -> int: ...
    @LBFGS.setter
    def LBFGS(self, val: int) -> None: ...
    @property
    def PertRule(self) -> int: ...
    @PertRule.setter
    def PertRule(self, val: int) -> None: ...
    @property
    def PrintFinal(self) -> int: ...
    @PrintFinal.setter
    def PrintFinal(self, val: int) -> None: ...
    @property
    def PrintLevel(self) -> int: ...
    @PrintLevel.setter
    def PrintLevel(self, val: int) -> None: ...
    @property
    def PrintParms(self) -> int: ...
    @PrintParms.setter
    def PrintParms(self, val: int) -> None: ...
    @property
    def Qdecay(self) -> ScalarType: ...
    @Qdecay.setter
    def Qdecay(self, val: FloatOrScalar) -> None: ...
    @property
    def QuadCutOff(self) -> ScalarType: ...
    @QuadCutOff.setter
    def QuadCutOff(self, val: FloatOrScalar) -> None: ...
    @property
    def QuadSafe(self) -> ScalarType: ...
    @QuadSafe.setter
    def QuadSafe(self, val: FloatOrScalar) -> None: ...
    @property
    def QuadStep(self) -> int: ...
    @QuadStep.setter
    def QuadStep(self, val: int) -> None: ...
    @property
    def SecantAmp(self) -> ScalarType: ...
    @SecantAmp.setter
    def SecantAmp(self, val: FloatOrScalar) -> None: ...
    @property
    def SmallCost(self) -> ScalarType: ...
    @SmallCost.setter
    def SmallCost(self, val: FloatOrScalar) -> None: ...
    @property
    def StopFac(self) -> ScalarType: ...
    @StopFac.setter
    def StopFac(self, val: FloatOrScalar) -> None: ...
    @property
    def StopRule(self) -> int: ...
    @StopRule.setter
    def StopRule(self, val: int) -> None: ...
    @property
    def SubCheck(self) -> int: ...
    @SubCheck.setter
    def SubCheck(self, val: int) -> None: ...
    @property
    def SubSkip(self) -> int: ...
    @SubSkip.setter
    def SubSkip(self, val: int) -> None: ...
    @property
    def UseCubic(self) -> int: ...
    @UseCubic.setter
    def UseCubic(self, val: int) -> None: ...
    @property
    def debug(self) -> int: ...
    @debug.setter
    def debug(self, val: int) -> None: ...
    @property
    def debugtol(self) -> ScalarType: ...
    @debugtol.setter
    def debugtol(self, val: FloatOrScalar) -> None: ...
    @property
    def delta(self) -> ScalarType: ...
    @delta.setter
    def delta(self, val: FloatOrScalar) -> None: ...
    @property
    def egrow(self) -> ScalarType: ...
    @egrow.setter
    def egrow(self, val: FloatOrScalar) -> None: ...
    @property
    def eps(self) -> ScalarType: ...
    @eps.setter
    def eps(self, val: FloatOrScalar) -> None: ...
    @property
    def eta0(self) -> ScalarType: ...
    @eta0.setter
    def eta0(self, val: FloatOrScalar) -> None: ...
    @property
    def eta1(self) -> ScalarType: ...
    @eta1.setter
    def eta1(self, val: FloatOrScalar) -> None: ...
    @property
    def eta2(self) -> ScalarType: ...
    @eta2.setter
    def eta2(self, val: FloatOrScalar) -> None: ...
    @property
    def feps(self) -> ScalarType: ...
    @feps.setter
    def feps(self, val: FloatOrScalar) -> None: ...
    @property
    def gamma(self) -> ScalarType: ...
    @gamma.setter
    def gamma(self, val: FloatOrScalar) -> None: ...
    @property
    def max_step(self) -> ScalarType: ...
    @max_step.setter
    def max_step(self, val: FloatOrScalar) -> None: ...
    @property
    def maxit(self) -> int: ...
    @maxit.setter
    def maxit(self, val: int) -> None: ...
    @property
    def memory(self) -> int: ...
    @memory.setter
    def memory(self, val: int) -> None: ...
    @property
    def nan_decay(self) -> ScalarType: ...
    @nan_decay.setter
    def nan_decay(self, val: FloatOrScalar) -> None: ...
    @property
    def nan_rho(self) -> ScalarType: ...
    @nan_rho.setter
    def nan_rho(self, val: FloatOrScalar) -> None: ...
    @property
    def neps(self) -> int: ...
    @neps.setter
    def neps(self, val: int) -> None: ...
    @property
    def nline(self) -> int: ...
    @nline.setter
    def nline(self, val: int) -> None: ...
    @property
    def nshrink(self) -> int: ...
    @nshrink.setter
    def nshrink(self, val: int) -> None: ...
    @property
    def nslow(self) -> int: ...
    @nslow.setter
    def nslow(self, val: int) -> None: ...
    @property
    def ntries(self) -> int: ...
    @ntries.setter
    def ntries(self, val: int) -> None: ...
    @property
    def psi0(self) -> ScalarType: ...
    @psi0.setter
    def psi0(self, val: FloatOrScalar) -> None: ...
    @property
    def psi1(self) -> ScalarType: ...
    @psi1.setter
    def psi1(self, val: FloatOrScalar) -> None: ...
    @property
    def psi2(self) -> ScalarType: ...
    @psi2.setter
    def psi2(self, val: FloatOrScalar) -> None: ...
    @property
    def psi_hi(self) -> ScalarType: ...
    @psi_hi.setter
    def psi_hi(self, val: FloatOrScalar) -> None: ...
    @property
    def psi_lo(self) -> ScalarType: ...
    @psi_lo.setter
    def psi_lo(self, val: FloatOrScalar) -> None: ...
    @property
    def qeps(self) -> ScalarType: ...
    @qeps.setter
    def qeps(self, val: FloatOrScalar) -> None: ...
    @property
    def qrestart(self) -> int: ...
    @qrestart.setter
    def qrestart(self, val: int) -> None: ...
    @property
    def qrule(self) -> ScalarType: ...
    @qrule.setter
    def qrule(self, val: FloatOrScalar) -> None: ...
    @property
    def restart_fac(self) -> ScalarType: ...
    @restart_fac.setter
    def restart_fac(self, val: FloatOrScalar) -> None: ...
    @property
    def rho(self) -> ScalarType: ...
    @rho.setter
    def rho(self, val: FloatOrScalar) -> None: ...
    @property
    def sigma(self) -> ScalarType: ...
    @sigma.setter
    def sigma(self, val: FloatOrScalar) -> None: ...
    @property
    def step(self) -> ScalarType: ...
    @step.setter
    def step(self, val: FloatOrScalar) -> None: ...
    @property
    def theta(self) -> ScalarType: ...
    @theta.setter
    def theta(self, val: FloatOrScalar) -> None: ...

class cg_stats:
    def __init__(self) -> None: ...
    @property
    def IterSub(self) -> int: ...
    @property
    def NumSub(self) -> int: ...
    @property
    def f(self) -> ScalarType: ...
    @property
    def gnorm(self) -> ScalarType: ...
    @property
    def iter(self) -> int: ...
    @property
    def nfunc(self) -> int: ...
    @property
    def ngrad(self) -> int: ...
