site_name: pycgdescent
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/alexfikl/pycgdescent

nav:
  - Home: index.md

theme:
  name: terminal
  features:
    - footer.prev_next
    - navigation.side.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default
      noclasses: true
  - pymdownx.inlinehilite
  - toc:
      baselevel: "1"
      toc_depth: "2"
      permalink: "#"
      permalink_title: Anchor link to this section for reference

extra_javascript:
  - js/custom.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css
