[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 85
target-version = ['py38']
exclude='\.eggs|\.git|\.mypy_cache|build|dist|\.pytest_cache|\.pytype'

[tool.ruff]
target-version = "py38"
line-length = 88
select = ["B", "E", "F", "I", "N", "Q", "U", "W"]
ignore = [
    # Module level import not at top of file
    "E402",
    # Import block is un-sorted or un-formatted
    "I001",
    ]

[tool.ruff.per-file-ignores]
"pycgdescent/_cg_descent.pyi" = ["N801", "N802"]
