[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "pybind11>=2.6",
    "setuptools>=42",
    "wheel",
]

[tool.black]
line-length = 88
target-version = ['py38']
exclude='\.eggs|\.git|\.mypy_cache|build|dist|\.pytest_cache|\.pytype'

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py38"
line-length = 88
select = ["A", "B", "C4", "E", "F", "FBT", "I", "ISC", "N", "Q", "S", "UP", "W"]
ignore = [
    # Module level import not at top of file
    "E402",
    # Import block is un-sorted or un-formatted
    "I001",
    # Use of assert detected
    "S101", "S102",
    ]

[tool.ruff.per-file-ignores]
"pycgdescent/_cg_descent.pyi" = ["A003", "N801", "N802"]

[tool.ruff.pyupgrade]
keep-runtime-typing = true
