[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 85
target-version = ['py38']
exclude='\.eggs|\.git|\.mypy_cache|build|dist|\.pytest_cache|\.pytype'

[tool.pyright]
pythonVersion = "3.8"
typeCheckingMode = "basic"
