[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "pybind11>=2.6",
    "setuptools>=42",
    "wheel",
]

[tool.black]
line-length = 88
target-version = ['py38']
exclude='\.eggs|\.git|\.mypy_cache|build|dist|\.pytest_cache|\.pytype'

[tool.isort]
profile = "black"

[tool.mypy]
warn_unused_ignores = true
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = [
    "importlib_metadata.*",
    "numpy.*",
    "matplotlib.*",
]
ignore_missing_imports = true

[tool.ruff]
target-version = "py38"
line-length = 88
select = ["A", "B", "C4", "E", "F", "FBT", "I", "ISC", "N", "Q", "S", "UP", "W"]
ignore = [
    "E402",
    "I001",
    "S101",
    "S102",
    "UP037",
]

[tool.ruff.per-file-ignores]
"pycgdescent/_cg_descent.pyi" = ["A003", "N801", "N802"]

[tool.ruff.pyupgrade]
keep-runtime-typing = true
