from collections.abc import Callable
from typing import Annotated

import numpy
from numpy.typing import NDArray

class cg_parameter:
    def __init__(self) -> None: ...
    @property
    def PrintFinal(self) -> int: ...
    @PrintFinal.setter
    def PrintFinal(self, arg: int, /) -> None: ...
    @property
    def PrintLevel(self) -> int: ...
    @PrintLevel.setter
    def PrintLevel(self, arg: int, /) -> None: ...
    @property
    def PrintParms(self) -> int: ...
    @PrintParms.setter
    def PrintParms(self, arg: int, /) -> None: ...
    @property
    def LBFGS(self) -> int: ...
    @LBFGS.setter
    def LBFGS(self, arg: int, /) -> None: ...
    @property
    def memory(self) -> int: ...
    @memory.setter
    def memory(self, arg: int, /) -> None: ...
    @property
    def SubCheck(self) -> int: ...
    @SubCheck.setter
    def SubCheck(self, arg: int, /) -> None: ...
    @property
    def SubSkip(self) -> int: ...
    @SubSkip.setter
    def SubSkip(self, arg: int, /) -> None: ...
    @property
    def eta0(self) -> float: ...
    @eta0.setter
    def eta0(self, arg: float, /) -> None: ...
    @property
    def eta1(self) -> float: ...
    @eta1.setter
    def eta1(self, arg: float, /) -> None: ...
    @property
    def eta2(self) -> float: ...
    @eta2.setter
    def eta2(self, arg: float, /) -> None: ...
    @property
    def AWolfe(self) -> int: ...
    @AWolfe.setter
    def AWolfe(self, arg: int, /) -> None: ...
    @property
    def AWolfeFac(self) -> float: ...
    @AWolfeFac.setter
    def AWolfeFac(self, arg: float, /) -> None: ...
    @property
    def Qdecay(self) -> float: ...
    @Qdecay.setter
    def Qdecay(self, arg: float, /) -> None: ...
    @property
    def nslow(self) -> int: ...
    @nslow.setter
    def nslow(self, arg: int, /) -> None: ...
    @property
    def StopRule(self) -> int: ...
    @StopRule.setter
    def StopRule(self, arg: int, /) -> None: ...
    @property
    def StopFac(self) -> float: ...
    @StopFac.setter
    def StopFac(self, arg: float, /) -> None: ...
    @property
    def PertRule(self) -> int: ...
    @PertRule.setter
    def PertRule(self, arg: int, /) -> None: ...
    @property
    def eps(self) -> float: ...
    @eps.setter
    def eps(self, arg: float, /) -> None: ...
    @property
    def egrow(self) -> float: ...
    @egrow.setter
    def egrow(self, arg: float, /) -> None: ...
    @property
    def QuadStep(self) -> int: ...
    @QuadStep.setter
    def QuadStep(self, arg: int, /) -> None: ...
    @property
    def QuadCutOff(self) -> float: ...
    @QuadCutOff.setter
    def QuadCutOff(self, arg: float, /) -> None: ...
    @property
    def QuadSafe(self) -> float: ...
    @QuadSafe.setter
    def QuadSafe(self, arg: float, /) -> None: ...
    @property
    def UseCubic(self) -> int: ...
    @UseCubic.setter
    def UseCubic(self, arg: int, /) -> None: ...
    @property
    def CubicCutOff(self) -> float: ...
    @CubicCutOff.setter
    def CubicCutOff(self, arg: float, /) -> None: ...
    @property
    def SmallCost(self) -> float: ...
    @SmallCost.setter
    def SmallCost(self, arg: float, /) -> None: ...
    @property
    def debug(self) -> int: ...
    @debug.setter
    def debug(self, arg: int, /) -> None: ...
    @property
    def debugtol(self) -> float: ...
    @debugtol.setter
    def debugtol(self, arg: float, /) -> None: ...
    @property
    def step(self) -> float: ...
    @step.setter
    def step(self, arg: float, /) -> None: ...
    @property
    def max_step(self) -> float: ...
    @max_step.setter
    def max_step(self, arg: float, /) -> None: ...
    @property
    def maxit(self) -> int: ...
    @maxit.setter
    def maxit(self, arg: int, /) -> None: ...
    @property
    def ntries(self) -> int: ...
    @ntries.setter
    def ntries(self, arg: int, /) -> None: ...
    @property
    def ExpandSafe(self) -> float: ...
    @ExpandSafe.setter
    def ExpandSafe(self, arg: float, /) -> None: ...
    @property
    def SecantAmp(self) -> float: ...
    @SecantAmp.setter
    def SecantAmp(self, arg: float, /) -> None: ...
    @property
    def neps(self) -> int: ...
    @neps.setter
    def neps(self, arg: int, /) -> None: ...
    @property
    def nshrink(self) -> int: ...
    @nshrink.setter
    def nshrink(self, arg: int, /) -> None: ...
    @property
    def nline(self) -> int: ...
    @nline.setter
    def nline(self, arg: int, /) -> None: ...
    @property
    def restart_fac(self) -> float: ...
    @restart_fac.setter
    def restart_fac(self, arg: float, /) -> None: ...
    @property
    def feps(self) -> float: ...
    @feps.setter
    def feps(self, arg: float, /) -> None: ...
    @property
    def nan_rho(self) -> float: ...
    @nan_rho.setter
    def nan_rho(self, arg: float, /) -> None: ...
    @property
    def nan_decay(self) -> float: ...
    @nan_decay.setter
    def nan_decay(self, arg: float, /) -> None: ...
    @property
    def rho(self) -> float: ...
    @rho.setter
    def rho(self, arg: float, /) -> None: ...
    @property
    def delta(self) -> float: ...
    @delta.setter
    def delta(self, arg: float, /) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, arg: float, /) -> None: ...
    @property
    def gamma(self) -> float: ...
    @gamma.setter
    def gamma(self, arg: float, /) -> None: ...
    @property
    def psi0(self) -> float: ...
    @psi0.setter
    def psi0(self, arg: float, /) -> None: ...
    @property
    def psi_lo(self) -> float: ...
    @psi_lo.setter
    def psi_lo(self, arg: float, /) -> None: ...
    @property
    def psi_hi(self) -> float: ...
    @psi_hi.setter
    def psi_hi(self, arg: float, /) -> None: ...
    @property
    def psi1(self) -> float: ...
    @psi1.setter
    def psi1(self, arg: float, /) -> None: ...
    @property
    def psi2(self) -> float: ...
    @psi2.setter
    def psi2(self, arg: float, /) -> None: ...
    @property
    def AdaptiveBeta(self) -> int: ...
    @AdaptiveBeta.setter
    def AdaptiveBeta(self, arg: int, /) -> None: ...
    @property
    def BetaLower(self) -> float: ...
    @BetaLower.setter
    def BetaLower(self, arg: float, /) -> None: ...
    @property
    def theta(self) -> float: ...
    @theta.setter
    def theta(self, arg: float, /) -> None: ...
    @property
    def qeps(self) -> float: ...
    @qeps.setter
    def qeps(self, arg: float, /) -> None: ...
    @property
    def qrule(self) -> float: ...
    @qrule.setter
    def qrule(self, arg: float, /) -> None: ...
    @property
    def qrestart(self) -> int: ...
    @qrestart.setter
    def qrestart(self, arg: int, /) -> None: ...

class cg_stats:
    @property
    def f(self) -> float: ...
    @property
    def gnorm(self) -> float: ...
    @property
    def iter(self) -> int: ...
    @property
    def IterSub(self) -> int: ...
    @property
    def NumSub(self) -> int: ...
    @property
    def nfunc(self) -> int: ...
    @property
    def ngrad(self) -> int: ...

class cg_iter_stats:
    @property
    def iter(self) -> int: ...
    @property
    def alpha(self) -> float: ...
    @property
    def x(self) -> Annotated[NDArray[numpy.float64], dict(writable=False)]: ...
    @property
    def f(self) -> float: ...
    @property
    def g(self) -> Annotated[NDArray[numpy.float64], dict(writable=False)]: ...
    @property
    def d(self) -> Annotated[NDArray[numpy.float64], dict(writable=False)]: ...

def cg_default(arg: cg_parameter, /) -> None: ...
def cg_descent(
    x: NDArray[numpy.float64],
    grad_tol: float,
    param: cg_parameter | None,
    value: Callable[[Annotated[NDArray[numpy.float64], dict(writable=False)]], float],
    grad: Callable[
        [
            NDArray[numpy.float64],
            Annotated[NDArray[numpy.float64], dict(writable=False)],
        ],
        None,
    ],
    valgrad: Callable[
        [
            NDArray[numpy.float64],
            Annotated[NDArray[numpy.float64], dict(writable=False)],
        ],
        float,
    ]
    | None,
    callback: Callable[[cg_iter_stats], int] | None,
    work: NDArray[numpy.float64] | None,
) -> tuple[NDArray[numpy.float64], cg_stats, int]: ...
