name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        python -m flake8 pycgdescent examples tests

  pylint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        python -m pylint pycgdescent examples/*.py tests/*.py

  pytest:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: pytest-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        python -m pytest

# vim: set ts=2 sw=2 et:
