name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 12 * * 0'

jobs:
  flake8:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        make flake8

  pylint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        make pylint

  mypy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: mypy-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        make mypy

  examples:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: examples-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        for ex in $(find examples -name "*.py"); do
          echo -e "\x1b[1;32m===> \x1b[97mRunning ${ex}\x1b[0m"
          python "${ex}"
        done

  pytest:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: pytest-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
    - uses: actions/checkout@v2
    -
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Main Script
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        python -m pytest

# vim: set ts=2 sw=2 et:
